on: [push, pull_request]
name: Lint
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Install linter
      run: go get -u golang.org/x/lint/golint
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint
      run: golint -set_exit_status